import time
from pprint import pprint

from generated_text_verification.generated_text_verification import generate_sentence_mapping

if __name__ == "__main__":
    original_texts = [
        "Kevin Chen-Chuan Chang is a Professor at University of Illinois Urbana-Champaign. Mr. Chang research primarily revolves around natural language processing, database and information retrieval. He has authored over 175 articles in prestigious journals and conferences, and his most famous article is A Comprehensive Survey of Graph Embedding: Problems, Techniques, and Applications. With a passion for innovation and a track record of collaborative research, Mr. Chang continues to contribute significantly to the ongoing discourse in natural language processing, linguistics, computational linguistics, graph theory and computer vision.",
        "Kevin Chenchuan Chang Professor\n(217) 244-2919\nkcchang@illinois.edu\n2134 Siebel Center for Comp Sci Education Ph.D. Electrial Engineering, Stanford University, 2001 Biography\nKevin Chen-Chuan Chang is a Professor in Computer Science, University of Illinois at Urbana-Champaign. He received a BS from National Taiwan University and PhD from Stanford University in Electrical Engineering. His research addresses large-scale information access and knowledge acquisition, for search, mining, and integration across structured and unstructured big data, with current focuses on Web search/mining and social media analytics. Research Statement\nI lead the FORWARD Data Lab group, which is part of the larger Data and Information Systems Laboratories, at the CS department of UIUC. Our research overall aims at bridging structured and unstructured data — to bring structured/semantic-rich access to the myriad and massive unstructured data which accounts for most of the world’s information. Therefore, our research spans natural language processing , data mining , data management/databases , information retrieval , and machine learning . As our approaches, we seek to be inspired by and learn from the data we are tackling-- i.e., we believe the key to tame big data is to learn the wisdom hidden in the large scale of the data. Research Interests\nNatural language processing, data mining, data management, and information retrieval with machine learning techniques, with emphasis on the application areas of Web and social media-based knowledge acquisition and organization across structured and unstructured data. Research Areas\nArtificial Intelligence\nData and Information Systems Teaching Honors UIUC List of Teachers Ranked as Excellent by Their Students, Fall 2001, Spring 2004, Fall 2005, Spring 2006, Fall 2010, Fall 2011, Fall 2019, Spring 2022, Spring 2023. Best Paper Award, International Conference on Advances in Social Networks Analysis and Mining (ASONAM), 2019. Recent Courses Taught\nCS 411 - Database Systems\nCS 412 CSP - Introduction to Data Mining\nCS 511 - Advanced Data Management\nCS 598 KCC (CS 598 KCO) - Listening to Social Universe",
    ]

    generated_texts = [
        "Kevin Chen-Chuan Chang is a distinguished Professor of Computer Science at the University of Illinois Urbana-Champaign. Having received a Bachelor's degree in Electrical Engineering from National Taiwan University and a PhD in Electrical Engineering from Stanford University in 2001, his academic career has been marked by a focus on natural language processing, database, and information retrieval. With over 175 published articles in esteemed journals and conferences and numerous awards and honors to his name, Chang's most well-known work is entitled \"A Comprehensive Survey of Graph Embedding: Problems, Techniques, and Applications.\" By heading the FORWARD Data Lab group and researching within the Data and Information Systems Laboratories at the CS department of UIUC, Chang continues to make a lasting impact on the fields of natural language processing, linguistics, computational linguistics, graph theory, and computer vision through his innovative and collaborative research endeavors.",
        'Dr. Kevin Chen-Chuan Chang is a distinguished professor at the University of Illinois Urbana-Champaign, renowned for his expertise in the fields of natural language processing, database systems, and information retrieval. Chang holds a Ph.D. in Electrical Engineering from Stanford University and has authored over 175 articles in prestigious journals and conferences. His renowned work, "A Comprehensive Survey of Graph Embedding: Problems, Techniques, and Applications," showcases his innovative approach to research. Dr. Chang holds numerous titles, including a List of Teachers Ranked as Excellent by Their Students from the University of Illinois at Urbana-Champaign, and he remains an influential figure in the ongoing discourse of natural language processing, linguistics, computational linguistics, graph theory, and computer vision.',
        'Kevin Chen-Chuan Chang, a professor at the University of Illinois Urbana-Champaign, has made significant contributions to natural language processing and information retrieval. Chang holds a Ph.D. in Electrical Engineering from Stanford University and has taught courses such as CS 411 - Database Systems, CS 412 CSP - Introduction to Data Mining, and CS 598 KCC - Listening to the Social Universe. His research focuses on large-scale information access and knowledge acquisition, primarily in web search, mining, and social media analytics. Through his expert knowledge in areas such as natural language processing, data mining, and information retrieval, Chang has authored over 175 articles in prestigious journals and conferences, with his most famous being "A Comprehensive Survey of Graph Embedding: Problems, Techniques, and Applications." As a part of the Data and Information Systems Laboratories at the CS department of UIUC, Chang continues to inspire innovations in research, further enriching his field and fostering ongoing discourse in areas like linguistics, computational linguistics, graph theory, and computer vision.',
    ]

    start_time = time.time()

    results = generate_sentence_mapping(
        generated_documents=generated_texts, source_documents=original_texts
    )

    runtime = time.time() - start_time

    for res in results:
        pprint(res)
        print("-----")

    print(f"\n### Runtime: {runtime}")